version: "3"
services:

  mysql_db:
    image: "mysql:8.0"
    volumes:
      - mysql_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE


  patientinfos:
    image: patient_info:1.0
    build:
      context: Mediscreen_patient_basic_infos
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db/mediscreen?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8081:8081"
    restart: always
    

volumes:
  mysql_db_data: {}